// Inlines web/index.html into a TypeScript module that the app shell loads into its WebView.
//   node scripts/build-web.mjs           generate once (runs on postinstall and before start)
//   node scripts/build-web.mjs --watch   regenerate whenever web/index.html changes
import fs from 'node:fs';
import path from 'node:path';
import { GAME_HTML, ROOT } from './lib/logic.mjs';

const OUT = path.join(ROOT, 'src', 'game', 'gameHtml.generated.ts');

function build() {
  const html = fs.readFileSync(GAME_HTML, 'utf8');
  const code = `// Generated by scripts/build-web.mjs from web/index.html. Do not edit by hand.\n` +
    `export const GAME_HTML: string = ${JSON.stringify(html)};\n`;
  const prev = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
  if (prev === code) return false;
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, code);
  return true;
}

const changed = build();
console.log(`${changed ? 'Wrote' : 'Up to date:'} ${path.relative(ROOT, OUT)}`);

if (process.argv.includes('--watch')) {
  let timer;
  fs.watch(path.dirname(GAME_HTML), (_, file) => {
    if (file && file !== path.basename(GAME_HTML)) return;
    clearTimeout(timer);
    timer = setTimeout(() => {
      try { if (build()) console.log(`${new Date().toLocaleTimeString()} rebuilt ${path.relative(ROOT, OUT)}`); }
      catch (err) { console.error(err.message); }
    }, 100);
  });
  console.log('Watching web/index.html…');
}
